version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        update-types:
          - 'patch'
          - 'minor'
          - 'major'
    commit-message:
      prefix: "chore"
      include: "scope"
