baseURL = 'https://cpeaustriajc.dev/'
languageCode = 'en-us'
title = 'John Carlo Austria'

[params]
  description = 'John Carlo Austria is a computer engineering student based in San Pablo City, Laguna, Philippines.'

[markup]
  [markup.highlight]
    noClasses = false
    guessSyntax = true
    tabWidth = 2
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ['html']
  section = ['html', 'rss']

[taxonomies]

[sitemap]
  changeFreq = 'weekly'
  priority = 0.5
